priority: false

turbo:
  linear_forward_min  : 0.05
  linear_forward_max  : 1.00
  linear_backward_min : 0.05
  linear_backward_max : 1.00
  angular_min : !degrees  30.0
  angular_max : !degrees 160.0
  steps       : 8
