<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:include filename="$(find mrp2_description)/urdf/wheels/wheel.transmission.xacro"/>
  <xacro:include filename="$(find mrp2_description)/urdf/wheels/wheel.gazebo.xacro"/>

  <xacro:macro name="wheel" params="side reflect radius width torque velocity separation parent">

    <link name="wheel_${side}_link">
      <inertial>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <mass
        value="0.70104587216324" />
      <inertia
        ixx="0.035"
        ixy="0"
        ixz="0"
        iyy="0.024"
        iyz="0"
        izz="0.035" />
    </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <mesh filename="package://mrp2_description/meshes/${side}_wheel.stl"/>
        </geometry>
        <material name="DarkGrey"/>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 1.5707 1.5707"/>
        <geometry>
          <cylinder radius="${radius}" length="${width}"/>
        </geometry>
      </collision>
    </link>

    <joint name="wheel_${side}_joint" type="continuous">
      <parent link="${parent}"/>
      <child link="wheel_${side}_link"/>
      <origin xyz="0 ${separation / 2} ${radius}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit effort="${torque*2}" velocity="${velocity / radius}"/>
    </joint>

    <gazebo reference="wheel_${side}_link">
      <material>Gazebo/DarkGrey</material>
    </gazebo>

    <xacro:wheel_gazebo side="${side}"/>

  </xacro:macro>
</robot>
