teleop:
  move:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: cmd_vel
    axis_mappings:
      -
        axis: 1
        target: linear.x
        scale: 1.0
      -
        axis: 3
        target: angular.z
        scale: 1.0

  joy_priority:
    type: action
    action_name: joy_priority_action
    buttons: [0]

  joy_turbo_decrease:
    type: action
    action_name: joy_turbo_decrease
    buttons: [4]

  joy_turbo_increase:
    type: action
    action_name: joy_turbo_increase
    buttons: [5]

  joy_turbo_angular_decrease:
    type: action
    action_name: joy_turbo_angular_decrease
    buttons: [4]

  joy_turbo_angular_increase:
    type: action
    action_name: joy_turbo_angular_increase
    buttons: [5]

  joy_turbo_reset:
    type: action
    action_name: joy_turbo_reset
    buttons: [8]
